/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                    '#faf5ee',
        'surface-bright':             '#faf5ee',
        'surface-dim':                '#dcd6cc',
        'surface-variant':            '#ece6dc',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f6f0e8',
        'surface-container':          '#f2ece4',
        'surface-container-high':     '#ece6dc',
        'surface-container-highest':  '#e6e0d6',
        'background':                 '#faf5ee',
        'on-background':              '#3a302a',
        'on-surface':                 '#3a302a',
        'on-surface-variant':         '#605850',
        'inverse-surface':            '#3a302a',
        'inverse-on-surface':         '#faf5ee',
        'primary':                    '#c2652a',
        'on-primary':                 '#ffffff',
        'primary-container':          '#e08850',
        'on-primary-container':       '#fbe8d8',
        'primary-fixed':              '#fbe8d8',
        'primary-fixed-dim':          '#f0a878',
        'on-primary-fixed':           '#401a08',
        'on-primary-fixed-variant':   '#8a4518',
        'inverse-primary':            '#f0a878',
        'surface-tint':               '#c2652a',
        'secondary':                  '#78706a',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#eae2da',
        'on-secondary-container':     '#605850',
        'secondary-fixed':            '#eae2da',
        'secondary-fixed-dim':        '#cec6be',
        'on-secondary-fixed':         '#2a2420',
        'on-secondary-fixed-variant': '#504840',
        'tertiary':                   '#8c3c3c',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#d47070',
        'on-tertiary-container':      '#3a2020',
        'tertiary-fixed':             '#fce0e0',
        'tertiary-fixed-dim':         '#e8a0a0',
        'on-tertiary-fixed':          '#2e1515',
        'on-tertiary-fixed-variant':  '#6e3030',
        'outline':                    '#9a9088',
        'outline-variant':            '#d8d0c8',
        'error':                      '#c0392b',
        'on-error':                   '#ffffff',
        'error-container':            '#fce4e0',
        'on-error-container':         '#7a1a10',
      },
      fontFamily: {
        headline: ['"EB Garamond"', 'serif'],
        display:  ['"EB Garamond"', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
